app:
    resource: "@AppBundle/Controller/"
    type:     annotation
account:
    resource: "@AcmeAccountBundle/Controller/"
    type:     annotation
admin:
    resource: "@AcmeAdminBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
JMSJobQueueBundle:
    resource: "@JMSJobQueueBundle/Controller/"
    type: annotation
    prefix: /jobs
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
