security:
    encoders:
        Acme\AdminBundle\Entity\Admin:
            algorithm: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        #fos_userbundle:
            #id: fos_user.user_provider.username_email
        administrators:
            entity: { class: AcmeAdminBundle:Admin }
        account_bundle:
            id: account_bundle.security.authentication.userprovider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/admin
            form_login:
                check_path: _admin_security_check
                login_path: _admin_login
                default_target_path: /admin/index
                always_use_default_target_path: true
                success_handler: authentication_handler
            logout:
                path:   _admin_logout
                target: /
            anonymous: ~
        main:
            pattern: ^/
            form_login:
                provider: account_bundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
