# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: Acme\AccountBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    account_bundle.security.authentication.userprovider:
        class:  Acme\AccountBundle\Security\UserProvider
        arguments:
            - @fos_user.user_manager
            - @service_container
    app.tokens.action_listener:
        class: AppBundle\EventListener\WechatTokenGetter
        #arguments: ["%tokens%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    app_bundle.doctrine.entity_listener_resolver:
        class: AppBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]
    app_bundle.entity_listener.payment:
        class: AppBundle\Entity\Listener\PaymentListener
        #arguments: [ "@acme_demo.mailer.user" ]
        tags:
            -  { name: doctrine.entity_listener }
