<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function getMessages($user, $offset = 0, $count = 20)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('AppBundle:Message', 'm')
            ->where('m.receiveUser = :user')
            ->orderby('m.id', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($count)
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
