<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductEventRepository extends EntityRepository
{
    public function getEvents($product = null, $order = null)
    {
        $prepare = $this->getEntityManager()
            ->createQueryBuilder()
            ->from('AppBundle:ProductEvent', 'e');
        if ( $product != null && $order == null) {
            $prepare = $prepare
                ->where('e.product = :product')
                ->setParameter('product', $product);
        }
        if ( $order != null && $product == null) {
            $prepare = $prepare
                ->where('e.order = :order')
                ->setParameter('order', $order);
        }
        if ( $order != null && $product != null) {
            $prepare = $prepare
                ->where('e.order = :order')
                ->setParameter('order', $order)
                ->orWhere('e.product = :product')
                ->setParameter('product', $product);
        }
        return $prepare
            ->getQuery()
            ->getResult();

    }
}
