<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getLikedProducts($user, $limit)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('AppBundle:Product', 'p')
            ->innerJoin('p.likeUsers', 'u')
            ->where('u.id = :user_id' )
            ->setParameter('user_id', $user->getId() )
            ->getQuery()
            ->setMaxResults($limit)
            ->getResult();
    }
}
