<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VerifyPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerifyPaymentRepository extends EntityRepository
{
}
